FROM python:3.11

WORKDIR /app

RUN pip install poetry

COPY ./pyproject.toml ./pyproject.toml
COPY ./poetry.lock ./poetry.lock

RUN poetry config virtualenvs.create false \
  && poetry export --only=migrations -f requirements.txt > requirements.txt \
  && pip install --no-cache-dir -r requirements.txt \
  && rm requirements.txt

COPY ./alembic .
COPY ./alembic.ini .

CMD alembic upgrade head
