version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tanks
      POSTGRES_HOST_AUTH_METHOD: trust

    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres@db:5432/tanks
      HOST: "0.0.0.0"
      PORT: 8000

  migrations:
    build:
      context: .
      dockerfile: Dockerfile-migrations
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres@db:5432/tanks

volumes:
  db_data:
