---
name: Run tests
on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install tox
        run: pip install tox

      - name: Cache tox environments
        uses: actions/cache@v1
        with:
          path: .tox
          key: tox|${{ hashFiles('tox.ini')}}

      - name: Test package
        run: tox
